"""
Q8. GAN that generates synthetic handwritten digits.

    DATASET NOTE
    ------------
    The real MNIST set (28x28, 70 000 images, Kaggle/Keras) is large to download in
    this session, so the script trains on scikit-learn's built-in `load_digits`
    (1 797 handwritten digits, 8x8 = a "MNIST-lite" set that ships with sklearn).
    The algorithm is identical - only the image size changes.
    For real MNIST use the Keras version at the bottom of this file.

    Generator     z(20) -> 128 -> 256 -> 64  (sigmoid)      [LeakyReLU inside]
    Discriminator x(64) -> 256 -> 128 -> 1   (sigmoid)
    Non-saturating GAN loss, Adam optimiser, everything written in NumPy.
"""
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

rng = np.random.default_rng(0)

# ---------------- data ----------------
X = load_digits().data / 16.0          # 1797 x 64 scaled to [0,1]
print(f"training images : {X.shape[0]}  of size 8x8 = {X.shape[1]} pixels")

ZDIM, IMG = 20, 64
lrelu  = lambda v, a=0.2: np.where(v > 0, v, a * v)
dlrelu = lambda v, a=0.2: np.where(v > 0, 1.0, a)
sig    = lambda v: 1 / (1 + np.exp(-np.clip(v, -30, 30)))

def init(shape):  # He initialisation
    return rng.standard_normal(shape) * np.sqrt(2 / shape[0])

# Generator params
G = {"W1": init((ZDIM, 128)), "b1": np.zeros(128),
     "W2": init((128, 256)),  "b2": np.zeros(256),
     "W3": init((256, IMG)),  "b3": np.zeros(IMG)}
# Discriminator params
D = {"W1": init((IMG, 256)),  "b1": np.zeros(256),
     "W2": init((256, 128)),  "b2": np.zeros(128),
     "W3": init((128, 1)),    "b3": np.zeros(1)}

class Adam:
    def __init__(s, p, lr=2e-4, b1=0.5, b2=0.999):
        s.p, s.lr, s.b1, s.b2, s.t = p, lr, b1, b2, 0
        s.m = {k: np.zeros_like(v) for k, v in p.items()}
        s.v = {k: np.zeros_like(v) for k, v in p.items()}
    def step(s, g):
        s.t += 1
        for k in s.p:
            s.m[k] = s.b1 * s.m[k] + (1 - s.b1) * g[k]
            s.v[k] = s.b2 * s.v[k] + (1 - s.b2) * g[k] ** 2
            mh = s.m[k] / (1 - s.b1 ** s.t); vh = s.v[k] / (1 - s.b2 ** s.t)
            s.p[k] -= s.lr * mh / (np.sqrt(vh) + 1e-8)

optG, optD = Adam(G), Adam(D)

def g_forward(z):
    h1 = lrelu(z  @ G["W1"] + G["b1"])
    h2 = lrelu(h1 @ G["W2"] + G["b2"])
    x  = sig(  h2 @ G["W3"] + G["b3"])
    return h1, h2, x

def d_forward(x):
    h1 = lrelu(x  @ D["W1"] + D["b1"])
    h2 = lrelu(h1 @ D["W2"] + D["b2"])
    o  = sig(  h2 @ D["W3"] + D["b3"])
    return h1, h2, o

def d_backward(x, h1, h2, o, dLdo_pre):
    """dLdo_pre = dLoss/d(logit)."""
    g = {}
    g["W3"] = h2.T @ dLdo_pre; g["b3"] = dLdo_pre.sum(0)
    d2 = (dLdo_pre @ D["W3"].T) * dlrelu(h1 @ D["W2"] + D["b2"])
    g["W2"] = h1.T @ d2;       g["b2"] = d2.sum(0)
    d1 = (d2 @ D["W2"].T) * dlrelu(x @ D["W1"] + D["b1"])
    g["W1"] = x.T @ d1;        g["b1"] = d1.sum(0)
    dx = d1 @ D["W1"].T
    return g, dx

BS, ITERS = 64, 6000
hist = []
for it in range(1, ITERS + 1):
    # ---------- train D ----------
    real = X[rng.integers(0, len(X), BS)]
    z    = rng.standard_normal((BS, ZDIM))
    _, _, fake = g_forward(z)
    rh1, rh2, ro = d_forward(real)
    fh1, fh2, fo = d_forward(fake)
    dloss = float(-np.mean(np.log(ro + 1e-8)) - np.mean(np.log(1 - fo + 1e-8)))
    gr, _ = d_backward(real, rh1, rh2, ro, (ro - 1) / BS)     # want D(real)=1
    gf, _ = d_backward(fake, fh1, fh2, fo, (fo - 0) / BS)     # want D(fake)=0
    optD.step({k: gr[k] + gf[k] for k in gr})

    # ---------- train G ----------
    z = rng.standard_normal((BS, ZDIM))
    h1, h2, fake = g_forward(z)
    fh1, fh2, fo = d_forward(fake)
    gloss = float(-np.mean(np.log(fo + 1e-8)))
    _, dx = d_backward(fake, fh1, fh2, fo, (fo - 1) / BS)     # non-saturating loss
    dpre3 = dx * fake * (1 - fake)                            # through sigmoid
    gg = {}
    gg["W3"] = h2.T @ dpre3; gg["b3"] = dpre3.sum(0)
    d2 = (dpre3 @ G["W3"].T) * dlrelu(h1 @ G["W2"] + G["b2"])
    gg["W2"] = h1.T @ d2;    gg["b2"] = d2.sum(0)
    d1 = (d2 @ G["W2"].T) * dlrelu(z @ G["W1"] + G["b1"])
    gg["W1"] = z.T @ d1;     gg["b1"] = d1.sum(0)
    optG.step(gg)

    hist.append((dloss, gloss))
    if it % 500 == 0:
        print(f"iter {it:5d}   D_loss = {dloss:.4f}   G_loss = {gloss:.4f}   "
              f"D(real) = {ro.mean():.3f}   D(fake) = {fo.mean():.3f}")

# ---------------- results ----------------
z = rng.standard_normal((16, ZDIM))
_, _, samples = g_forward(z)
fig, ax = plt.subplots(4, 8, figsize=(11, 5.5))
for i in range(16):
    r, c = divmod(i, 4)
    ax[r, c].imshow(X[i].reshape(8, 8), cmap="gray"); ax[r, c].axis("off")
    ax[r, c + 4].imshow(samples[i].reshape(8, 8), cmap="gray"); ax[r, c + 4].axis("off")
ax[0, 1].set_title("REAL digits (sklearn)", fontsize=11)
ax[0, 5].set_title("GENERATED by the GAN", fontsize=11)
plt.tight_layout(); plt.savefig("/mnt/user-data/outputs/q8_gan_samples.png", dpi=130)

plt.figure(figsize=(6.5, 4))
plt.plot([h[0] for h in hist], label="Discriminator loss", lw=.8)
plt.plot([h[1] for h in hist], label="Generator loss",     lw=.8)
plt.xlabel("Iteration"); plt.ylabel("Loss"); plt.legend(); plt.grid(alpha=.3)
plt.title("Q8 - GAN adversarial training")
plt.tight_layout(); plt.savefig("/mnt/user-data/outputs/q8_gan_loss.png", dpi=130)
print("\n[Figures saved: q8_gan_samples.png , q8_gan_loss.png]")

# ----------------------------------------------------------------------
# REAL MNIST VERSION (needs tensorflow, downloads MNIST automatically):
#
# from tensorflow.keras.datasets import mnist
# from tensorflow.keras import layers, models, optimizers
# import tensorflow as tf, numpy as np
# (x,_),_ = mnist.load_data(); x = (x.astype('float32')-127.5)/127.5
# x = x.reshape(-1,784)
# gen = models.Sequential([layers.Dense(256,input_dim=100), layers.LeakyReLU(0.2),
#                          layers.Dense(512), layers.LeakyReLU(0.2),
#                          layers.Dense(784, activation='tanh')])
# dis = models.Sequential([layers.Dense(512,input_dim=784), layers.LeakyReLU(0.2),
#                          layers.Dense(256), layers.LeakyReLU(0.2),
#                          layers.Dense(1, activation='sigmoid')])
# dis.compile(optimizers.Adam(2e-4,0.5),'binary_crossentropy')
# dis.trainable=False
# gan = models.Sequential([gen,dis]); gan.compile(optimizers.Adam(2e-4,0.5),'binary_crossentropy')
# for epoch in range(10000):
#     idx=np.random.randint(0,len(x),64); real=x[idx]
#     z=np.random.normal(0,1,(64,100)); fake=gen.predict(z,verbose=0)
#     dis.trainable=True
#     dis.train_on_batch(real,np.ones((64,1))*0.9); dis.train_on_batch(fake,np.zeros((64,1)))
#     dis.trainable=False
#     gan.train_on_batch(np.random.normal(0,1,(64,100)), np.ones((64,1)))
